reword and add clean/install

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -17,6 +17,22 @@ personal) ;;
   ;;
 esac
 
+case $1 in
+work) ;;
+
+trayio) ;;
+
+personal) ;;
+
+*)
+  echo "Invalid configuration."
+  echo "Valid options:"
+  echo "- $0 clean (cleans all stowed folders)"
+  echo "- $0 install (stows the files)"
+  exit 1
+  ;;
+esac
+
 # First install brew on a mac
 if [ $(uname) = "Darwin" ]; then
   which brew &>/dev/null ||
@@ -42,7 +58,7 @@ else
 fi
 
 # Stow install our apps
-$HOME/dotfiles/install $1
+$HOME/dotfiles/run $1 $2
 
 # Run the update
 if [ "$1" = "mac" ]; then
diff --git a/run b/run
--- a/run
+++ b/run
@@ -19,9 +19,24 @@ personal)
     ;;
 esac
 
+case $2 in
+clean | delete | wipe)
+    command=-D
+    wording="Unstowing"
+    ;;
+install)
+    command=-R
+    wording="Stowing"
+    ;;
+*)
+    echo "Invalid group"
+    exit 1
+    ;;
+esac
+
 for folder in $(echo $folders | sed "s/,/ /g"); do
-    echo -n "Stowing $folder...  "
-    output=$(stow -R $folder 2>&1)
+    echo -n "$wording $folder...  "
+    output=$(stow $command $folder 2>&1)
     result=$?
     if [ $result -eq 0 ]; then
         echo "ok"
